/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedTemperatureCheckInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getFeverResult"
      | "getTemperature"
      | "protocolId"
      | "submitAndCheck"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFeverResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTemperature",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitAndCheck",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFeverResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTemperature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitAndCheck",
    data: BytesLike
  ): Result;
}

export interface EncryptedTemperatureCheck extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedTemperatureCheck;
  waitForDeployment(): Promise<this>;

  interface: EncryptedTemperatureCheckInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFeverResult: TypedContractMethod<[], [string], "view">;

  getTemperature: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitAndCheck: TypedContractMethod<
    [
      encryptedTemperature: BytesLike,
      encryptedThreshold: BytesLike,
      inputProof: BytesLike,
      thresholdProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFeverResult"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTemperature"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitAndCheck"
  ): TypedContractMethod<
    [
      encryptedTemperature: BytesLike,
      encryptedThreshold: BytesLike,
      inputProof: BytesLike,
      thresholdProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
